import { CertificateDataFields, CertificateDesign, IssuedCertificate } from '../types/certificate';
import { PAPER_SIZE_PRESETS } from './sizes';

export const DEFAULT_DATA_FIELDS: CertificateDataFields = {
  recipient_name: 'Alex Johnson',
  certificate_title: 'CERTIFICATE OF HIGHEST EXCELLENCE',
  course_name: 'Advanced Full-Stack Systems & Distributed Cloud Architecture',
  description: 'In formal recognition of outstanding dedication, demonstrated technical mastery, and exemplary academic performance throughout the intensive professional certification curriculum.',
  organization_name: 'CMAKER Global Academy',
  organization_address: 'One Innovation Plaza, San Francisco, CA 94105',
  issue_date: 'September 5, 2026',
  expiry_date: 'September 5, 2029',
  certificate_id: 'CERT-2026-000001',
  instructor_name: 'Dr. Helena Vance',
  instructor_position: 'Academic Director & Chancellor',
  score: '98.5 / 100 (Top 1% Merit)',
  grade: 'Summa Cum Laude',
  event_name: 'Global Engineering Leadership Summit 2026',
  custom_fields: {
    faculty: 'Faculty of Computer Science & Advanced Systems',
    accreditation: 'ISO-9001:2026 & ABET Global Accreditation Standards',
    dean_name: 'Prof. Marcus Sterling, Ph.D.',
    dean_position: 'Dean of Academic Faculty',
    honors: 'Honor Roll with Highest Distinction',
    credits: '60 Continuing Education Units (CEU)'
  }
};

// Primary handwritten signature (Director)
export const DEFAULT_SIGNATURE_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 120" width="320" height="120"><path d="M25 75 C 60 20, 80 15, 95 65 C 105 95, 120 100, 140 40 C 155 10, 170 30, 180 80 C 195 70, 220 50, 240 60 C 260 70, 275 65, 295 45 M70 65 Q 160 40 280 65" fill="none" stroke="%231e293b" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`;

// Secondary handwritten signature (Dean / Chancellor)
export const SECOND_SIGNATURE_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 120" width="320" height="120"><path d="M30 65 C 50 15, 75 25, 85 70 C 95 90, 110 95, 125 45 C 135 20, 150 20, 160 60 C 175 40, 200 35, 220 55 C 240 75, 260 50, 280 40 M60 85 Q 160 65 290 80" fill="none" stroke="%230f172a" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`;

// Default Organization Logo SVG
export const DEFAULT_LOGO_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><circle cx="50" cy="50" r="46" fill="%231e293b"/><path d="M50 18 L76 34 L76 66 L50 82 L24 66 L24 34 Z" fill="none" stroke="%23d4af37" stroke-width="3.5"/><circle cx="50" cy="50" r="14" fill="%23d4af37"/><path d="M42 50 L47 55 L58 44" fill="none" stroke="%230f172a" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`;

// Official Accreditation Badge SVG
export const ACCREDITATION_BADGE_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" width="120" height="120"><polygon points="60,6 74,18 92,18 98,34 114,44 110,62 118,78 106,92 104,110 86,114 74,124 60,116 46,124 34,114 16,110 14,92 2,78 10,62 6,44 22,34 28,18 46,18" fill="%23d4af37"/><circle cx="60" cy="65" r="42" fill="%230f172a"/><circle cx="60" cy="65" r="37" fill="none" stroke="%23d4af37" stroke-width="1.5"/><text x="60" y="52" fill="%23d4af37" font-size="7.5" font-family="sans-serif" font-weight="bold" text-anchor="middle" letter-spacing="1">ACCREDITED</text><polygon points="60,58 63,65 71,65 65,70 67,77 60,73 53,77 55,70 49,65 57,65" fill="%23d4af37"/><text x="60" y="88" fill="%23ffffff" font-size="6.5" font-family="sans-serif" font-weight="bold" text-anchor="middle" letter-spacing="1">ISO 9001:2026</text></svg>`;

// Gold Medal with Ribbons SVG
export const GOLD_MEDAL_RIBBON_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 130" width="100" height="130"><polygon points="35,65 25,120 50,105 75,120 65,65" fill="%231e3a8a"/><polygon points="40,65 30,120 50,108 70,120 60,65" fill="%23b91c1c"/><circle cx="50" cy="50" r="38" fill="%23d4af37"/><circle cx="50" cy="50" r="32" fill="%23f59e0b"/><polygon points="50,26 56,38 70,38 58,47 62,60 50,52 38,60 42,47 30,38 44,38" fill="%23ffffff"/></svg>`;

// Safety & Compliance Shield Badge SVG
export const SAFETY_SHIELD_BADGE_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 115" width="100" height="115"><path d="M50 5 L88 22 C88 65 50 105 50 105 C50 105 12 65 12 22 Z" fill="%23d97706"/><path d="M50 12 L80 26 C80 62 50 96 50 96 C50 96 20 62 20 26 Z" fill="%230f172a"/><path d="M36 52 L46 62 L66 40" fill="none" stroke="%23f59e0b" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/><text x="50" y="80" fill="%23ffffff" font-size="7.5" font-family="sans-serif" font-weight="bold" text-anchor="middle" letter-spacing="1">CERTIFIED</text></svg>`;

// Global Education & Laurel Star Crest SVG
export const GLOBAL_EDUCATION_CREST_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><circle cx="50" cy="50" r="46" fill="%230f172a"/><circle cx="50" cy="50" r="40" fill="none" stroke="%23d4af37" stroke-width="2"/><path d="M50 20 L58 36 L76 36 L62 47 L67 64 L50 54 L33 64 L38 47 L24 36 L42 36 Z" fill="%23d4af37"/><path d="M30 75 C40 84 60 84 70 75" fill="none" stroke="%23d4af37" stroke-width="2.5" stroke-linecap="round"/></svg>`;

export const DEFAULT_CERTIFICATE_DESIGN: CertificateDesign = {
  id: 'default-academic-gold',
  name: 'Classic Academic Excellence',
  dimensions: PAPER_SIZE_PRESETS['a4-landscape'].dimensions,
  background: {
    type: 'color',
    color: '#FCFAF5' // Soft ivory parchment
  },
  dataFields: DEFAULT_DATA_FIELDS,
  elements: [
    // 1. Outer Border Frame (Ornamental with gold corner rosettes)
    {
      id: 'border-main',
      name: 'Outer Border Frame',
      type: 'border',
      borderStyle: 'ornamental',
      strokeColor: '#C5A059',
      secondaryColor: '#1E293B',
      strokeWidth: 4,
      inset: 22,
      hasCorners: true,
      x: 0,
      y: 0,
      width: 1123,
      height: 794,
      rotation: 0,
      opacity: 1,
      isLocked: true,
      isVisible: true
    },
    // 2. Corner Filigree Ornaments
    {
      id: 'ornament-tl',
      name: 'Top-Left Corner Flourish',
      type: 'shape',
      shapeType: 'corner-ornament',
      fillColor: '#C5A059',
      strokeColor: '#C5A059',
      strokeWidth: 2,
      x: 28,
      y: 28,
      width: 70,
      height: 70,
      rotation: 0,
      opacity: 0.85,
      isLocked: true,
      isVisible: true
    },
    {
      id: 'ornament-tr',
      name: 'Top-Right Corner Flourish',
      type: 'shape',
      shapeType: 'corner-ornament',
      fillColor: '#C5A059',
      strokeColor: '#C5A059',
      strokeWidth: 2,
      x: 1025,
      y: 28,
      width: 70,
      height: 70,
      rotation: 90,
      opacity: 0.85,
      isLocked: true,
      isVisible: true
    },
    // 3. Left Top Accreditation Badge
    {
      id: 'badge-iso',
      name: 'Accreditation Badge',
      type: 'image',
      src: ACCREDITATION_BADGE_SVG,
      preserveAspectRatio: true,
      x: 80,
      y: 45,
      width: 65,
      height: 65,
      rotation: 0,
      opacity: 0.95,
      isLocked: false,
      isVisible: true
    },
    // 4. Center Organization Crest Logo
    {
      id: 'logo-top',
      name: 'Organization Crest Logo',
      type: 'image',
      src: DEFAULT_LOGO_SVG,
      preserveAspectRatio: true,
      x: 521,
      y: 42,
      width: 80,
      height: 80,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },
    // 5. Right Top Presidential Medallion
    {
      id: 'badge-medal',
      name: 'Medal Ribbon Emblem',
      type: 'image',
      src: GOLD_MEDAL_RIBBON_SVG,
      preserveAspectRatio: true,
      x: 975,
      y: 45,
      width: 55,
      height: 72,
      rotation: 0,
      opacity: 0.95,
      isLocked: false,
      isVisible: true
    },
    // 6. Organization Name Header
    {
      id: 'text-org',
      name: 'Organization Header',
      type: 'text',
      text: '{{organization_name}}',
      fontSize: 18,
      fontFamily: "'Inter', sans-serif",
      fontWeight: 700,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#1E293B',
      textAlign: 'center',
      letterSpacing: 4,
      lineHeight: 1.2,
      textTransform: 'uppercase',
      x: 261,
      y: 130,
      width: 600,
      height: 25,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },
    // 7. Faculty / Academic Division Subheader
    {
      id: 'text-faculty',
      name: 'Academic Division',
      type: 'text',
      text: 'FACULTY OF ADVANCED SYSTEMS & DIGITAL SCIENCES • DIVISION OF CREDENTIALS',
      fontSize: 10,
      fontFamily: "'Inter', sans-serif",
      fontWeight: 600,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#854D0E',
      textAlign: 'center',
      letterSpacing: 2.5,
      lineHeight: 1.2,
      textTransform: 'uppercase',
      x: 161,
      y: 156,
      width: 800,
      height: 18,
      rotation: 0,
      opacity: 0.9,
      isLocked: false,
      isVisible: true
    },
    // 8. Latin Motto Ribbon Banner
    {
      id: 'text-motto',
      name: 'Institutional Motto',
      type: 'text',
      text: '« VERITAS • EXCELLENTIA • INTEGRITAS • MCMXCVIII »',
      fontSize: 9.5,
      fontFamily: "'Libre Baskerville', Garamond, serif",
      fontWeight: 400,
      fontStyle: 'italic',
      textDecoration: 'none',
      color: '#94A3B8',
      textAlign: 'center',
      letterSpacing: 3,
      lineHeight: 1.2,
      x: 261,
      y: 175,
      width: 600,
      height: 16,
      rotation: 0,
      opacity: 0.85,
      isLocked: false,
      isVisible: true
    },
    // 9. Certificate Main Title
    {
      id: 'text-title',
      name: 'Certificate Title',
      type: 'text',
      text: '{{certificate_title}}',
      fontSize: 36,
      fontFamily: "'Playfair Display', Georgia, serif",
      fontWeight: 800,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#0F172A',
      textAlign: 'center',
      letterSpacing: 3,
      lineHeight: 1.2,
      textTransform: 'uppercase',
      x: 111,
      y: 198,
      width: 900,
      height: 50,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },
    // 10. Presentation Subtitle
    {
      id: 'text-subtitle',
      name: 'Presentation Subtitle',
      type: 'text',
      text: 'UPON THE RECOMMENDATION OF THE ACADEMIC COUNCIL, THIS OFFICIAL DIPLOMA IS CONFERRED TO',
      fontSize: 10,
      fontFamily: "'Inter', sans-serif",
      fontWeight: 600,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#64748B',
      textAlign: 'center',
      letterSpacing: 2,
      lineHeight: 1.2,
      textTransform: 'uppercase',
      x: 161,
      y: 254,
      width: 800,
      height: 18,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },
    // 11. Recipient Name (Large, prestigious Playfair Display)
    {
      id: 'text-recipient',
      name: 'Recipient Name',
      type: 'text',
      text: '{{recipient_name}}',
      fontSize: 48,
      fontFamily: "'Playfair Display', Georgia, serif",
      fontWeight: 700,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#C5A059',
      textAlign: 'center',
      letterSpacing: 1.5,
      lineHeight: 1.2,
      x: 111,
      y: 280,
      width: 900,
      height: 65,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },
    // 12. Ornate Vintage Center Divider with Diamond
    {
      id: 'divider-ornate',
      name: 'Ornate Diamond Divider',
      type: 'shape',
      shapeType: 'divider',
      fillColor: '#C5A059',
      strokeColor: '#C5A059',
      strokeWidth: 1.5,
      x: 361,
      y: 350,
      width: 400,
      height: 16,
      rotation: 0,
      opacity: 0.9,
      isLocked: false,
      isVisible: true
    },
    // 13. Honors & Distinction Ribbon Pill
    {
      id: 'text-honors-pill',
      name: 'Honors Pill Badge',
      type: 'text',
      text: '★ SUMMA CUM LAUDE • HIGHEST DISTINCTION • RANK: TOP 1% ★',
      fontSize: 10.5,
      fontFamily: "'Inter', sans-serif",
      fontWeight: 700,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#854D0E',
      textAlign: 'center',
      letterSpacing: 2,
      lineHeight: 1.2,
      textTransform: 'uppercase',
      x: 261,
      y: 374,
      width: 600,
      height: 20,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },
    // 14. Description Body Text
    {
      id: 'text-desc',
      name: 'Certificate Description',
      type: 'text',
      text: '{{description}}',
      fontSize: 14,
      fontFamily: "'Libre Baskerville', Garamond, serif",
      fontWeight: 400,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#475569',
      textAlign: 'center',
      letterSpacing: 0.3,
      lineHeight: 1.6,
      x: 161,
      y: 402,
      width: 800,
      height: 48,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },
    // 15. Program & Competencies Specialization Box
    {
      id: 'text-course',
      name: 'Program Specialization Box',
      type: 'text',
      text: 'SPECIALIZATION: {{course_name}}',
      fontSize: 12.5,
      fontFamily: "'Inter', sans-serif",
      fontWeight: 700,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#1E293B',
      textAlign: 'center',
      letterSpacing: 1.5,
      lineHeight: 1.2,
      textTransform: 'uppercase',
      x: 161,
      y: 460,
      width: 800,
      height: 22,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },
    // 16. Academic Metrics Strip (Score, GPA, Credits)
    {
      id: 'text-metrics',
      name: 'Academic Metrics Strip',
      type: 'text',
      text: 'ACADEMIC SCORE: {{score}} • GPA: 3.98/4.00 • ACCREDITED 60 CEU UNITS',
      fontSize: 10,
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 600,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#64748B',
      textAlign: 'center',
      letterSpacing: 1,
      lineHeight: 1.2,
      x: 211,
      y: 486,
      width: 700,
      height: 18,
      rotation: 0,
      opacity: 0.9,
      isLocked: false,
      isVisible: true
    },

    // 17. Left Authority: Dean of Academic Affairs
    {
      id: 'sig-dean',
      name: 'Dean Signature',
      type: 'signature',
      src: SECOND_SIGNATURE_SVG,
      signerName: 'Prof. Marcus Sterling',
      signerTitle: 'Dean of Academic Faculty',
      isTransparent: true,
      x: 110,
      y: 535,
      width: 180,
      height: 60,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },
    {
      id: 'line-sig-dean',
      name: 'Dean Signature Line',
      type: 'shape',
      shapeType: 'line',
      fillColor: '#C5A059',
      strokeColor: '#C5A059',
      strokeWidth: 1.5,
      x: 90,
      y: 600,
      width: 220,
      height: 2,
      rotation: 0,
      opacity: 0.8,
      isLocked: false,
      isVisible: true
    },
    {
      id: 'text-sig-dean-name',
      name: 'Dean Name & Title',
      type: 'text',
      text: 'Prof. Marcus Sterling, Ph.D.\nDean of Academic Faculty',
      fontSize: 11,
      fontFamily: "'Inter', sans-serif",
      fontWeight: 600,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#1E293B',
      textAlign: 'center',
      letterSpacing: 0.5,
      lineHeight: 1.3,
      x: 90,
      y: 608,
      width: 220,
      height: 32,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },

    // 18. Official Center Embossed Gold Seal
    {
      id: 'seal-official',
      name: 'Official Gold Foil Seal',
      type: 'seal',
      sealType: 'certified',
      primaryText: 'OFFICIAL EMBOSSED SEAL',
      secondaryText: 'ACADEMIC MERIT & EXCELLENCE',
      centerIcon: 'crest',
      sealColor: '#C5A059',
      accentColor: '#1E293B',
      outerRingStyle: 'double-ring',
      x: 499,
      y: 520,
      width: 125,
      height: 125,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },

    // 19. Right Authority: Academic Director & Chancellor
    {
      id: 'sig-director',
      name: 'Director Signature',
      type: 'signature',
      src: DEFAULT_SIGNATURE_SVG,
      signerName: 'Dr. Helena Vance',
      signerTitle: 'Academic Director & Chancellor',
      isTransparent: true,
      x: 830,
      y: 535,
      width: 180,
      height: 60,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },
    {
      id: 'line-sig-dir',
      name: 'Director Signature Line',
      type: 'shape',
      shapeType: 'line',
      fillColor: '#C5A059',
      strokeColor: '#C5A059',
      strokeWidth: 1.5,
      x: 810,
      y: 600,
      width: 220,
      height: 2,
      rotation: 0,
      opacity: 0.8,
      isLocked: false,
      isVisible: true
    },
    {
      id: 'text-sig-dir-name',
      name: 'Director Name & Title',
      type: 'text',
      text: '{{instructor_name}}\n{{instructor_position}}',
      fontSize: 11,
      fontFamily: "'Inter', sans-serif",
      fontWeight: 600,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#1E293B',
      textAlign: 'center',
      letterSpacing: 0.5,
      lineHeight: 1.3,
      x: 810,
      y: 608,
      width: 220,
      height: 32,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },

    // 20. QR Verification Barcode (Bottom Center-Left)
    {
      id: 'qr-verify',
      name: 'Tamper-Proof QR Code',
      type: 'qrcode',
      urlPattern: 'https://cmaker.app/verify/{{certificate_id}}',
      fgColor: '#0F172A',
      bgColor: '#FFFFFF',
      includeLabel: true,
      label: 'Scan to Verify Authenticity',
      errorCorrectionLevel: 'H',
      x: 350,
      y: 545,
      width: 85,
      height: 85,
      rotation: 0,
      opacity: 1,
      isLocked: false,
      isVisible: true
    },

    // 21. Date & Registration Metadata (Bottom Left)
    {
      id: 'text-date-box',
      name: 'Date and ID Stamp',
      type: 'text',
      text: 'DATE OF ISSUE: {{issue_date}}\nEXPIRATION: {{expiry_date}}\nID: {{certificate_id}}',
      fontSize: 10,
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 600,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#475569',
      textAlign: 'left',
      letterSpacing: 0.5,
      lineHeight: 1.4,
      x: 90,
      y: 660,
      width: 300,
      height: 48,
      rotation: 0,
      opacity: 0.9,
      isLocked: false,
      isVisible: true
    },

    // 22. Bottom Security Microprint Strip (Prevents fraud, fills footer space elegantly)
    {
      id: 'text-security-strip',
      name: 'Security Microprint Strip',
      type: 'text',
      text: '• SECURE DIGITAL CREDENTIAL • REGISTERED ON PERMANENT IMMUTABLE LEDGER • ISO/IEC 27001 AUDITED • TAMPER-EVIDENT ID: {{certificate_id}} •',
      fontSize: 8.5,
      fontFamily: "'JetBrains Mono', monospace",
      fontWeight: 600,
      fontStyle: 'normal',
      textDecoration: 'none',
      color: '#94A3B8',
      textAlign: 'center',
      letterSpacing: 2,
      lineHeight: 1.2,
      x: 61,
      y: 720,
      width: 1000,
      height: 16,
      rotation: 0,
      opacity: 0.8,
      isLocked: true,
      isVisible: true
    }
  ]
};

// Initial Seed Certificates for Testing & Verification
export const INITIAL_ISSUED_CERTIFICATES: IssuedCertificate[] = [
  {
    id: 'CERT-2026-000001',
    projectId: 'default-project-1',
    recipientName: 'Alex Johnson',
    recipientEmail: 'alex.johnson@example.com',
    title: 'Certificate of Highest Excellence',
    organization: 'CMAKER Global Academy',
    issueDate: '2026-09-05',
    expiryDate: '2029-09-05',
    status: 'valid',
    issuerName: 'Dr. Helena Vance',
    issuerPosition: 'Academic Director & Chancellor',
    designSnapshot: DEFAULT_CERTIFICATE_DESIGN,
    createdAt: '2026-09-05T10:00:00.000Z',
    scanCount: 18,
    verificationHash: '8f94a2b7c6d1e3f5a0b9c8d7e6f5a4b3c2d1e0f9'
  },
  {
    id: 'CERT-2026-000002',
    projectId: 'default-project-2',
    recipientName: 'Marcus Vance',
    recipientEmail: 'marcus.v@cloudtech.io',
    title: 'Enterprise Cloud Architect Certification',
    organization: 'Global Tech Institute',
    issueDate: '2026-08-15',
    expiryDate: '2028-08-15',
    status: 'valid',
    issuerName: 'Sarah Jenkins',
    issuerPosition: 'VP of Engineering',
    designSnapshot: DEFAULT_CERTIFICATE_DESIGN,
    createdAt: '2026-08-15T09:30:00.000Z',
    scanCount: 32,
    verificationHash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b'
  },
  {
    id: 'CERT-2026-000003',
    projectId: 'default-project-3',
    recipientName: 'Robert Sterling',
    recipientEmail: 'r.sterling@corp.com',
    title: 'Leadership in Strategic Management',
    organization: 'Apex Executive Academy',
    issueDate: '2026-01-10',
    expiryDate: '2026-07-10',
    status: 'expired',
    issuerName: 'Prof. Arthur Pendelton',
    issuerPosition: 'Dean of Executive Studies',
    designSnapshot: DEFAULT_CERTIFICATE_DESIGN,
    createdAt: '2026-01-10T14:20:00.000Z',
    scanCount: 7,
    verificationHash: '5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1a2b3c4d'
  },
  {
    id: 'CERT-2026-000004',
    projectId: 'default-project-4',
    recipientName: 'Chloe Bennett',
    recipientEmail: 'chloe.b@designhub.co',
    title: 'Certified UX Research Specialist',
    organization: 'Design Excellence Guild',
    issueDate: '2026-05-20',
    expiryDate: '2027-05-20',
    status: 'revoked',
    issuerName: 'Evelyn Reed',
    issuerPosition: 'Chief Design Officer',
    revocationReason: 'Credentials revoked due to academic integrity violation under policy Section 4.2.',
    revokedAt: '2026-07-01T11:00:00.000Z',
    designSnapshot: DEFAULT_CERTIFICATE_DESIGN,
    createdAt: '2026-05-20T16:45:00.000Z',
    scanCount: 4,
    verificationHash: '3a4b5c6d7e8f9a0b1a2b3c4d5e6f7a8b9c0d1e2f'
  }
];

export const SAMPLE_CSV_CONTENT = `name,email,course,date,score,certificate_id
Jane Smith,jane.smith@example.com,Full-Stack Engineering,2026-09-01,98,CERT-2026-000101
Michael Chen,michael.chen@tech.org,Full-Stack Engineering,2026-09-01,95,CERT-2026-000102
Amira Zahra,amira.zahra@dev.io,Full-Stack Engineering,2026-09-01,99,CERT-2026-000103
David Miller,david.m@innovate.co,Full-Stack Engineering,2026-09-01,92,CERT-2026-000104
Sophia Rodriguez,sophia.r@agency.com,Full-Stack Engineering,2026-09-01,96,CERT-2026-000105
Kenji Sato,kenji.sato@global.jp,Full-Stack Engineering,2026-09-01,94,CERT-2026-000106`;
